# Generated by Django 5.0.1 on 2024-06-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('images', models.ImageField(upload_to='products')),
            ],
        ),
    ]
